name: user_agent
description: A Dart user agent detection library.
version: 1.0.0-beta
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/user_agent
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  r2d2: '>=0.1.1 <0.2.0'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
